services:
  scraper:
    build: .
    container_name: linkedin-scraper
    ports:
      - "4008:4008"
    environment:
      - HEADLESS=true
      - PORT=4008
      - SEARXNG_URL=http://searxng:8080
      # - WEBHOOK_URL=https://n8n.b2botix.ai/webhook/linkedin-filter
    volumes:
      - ./output:/app/output
    restart: unless-stopped
    depends_on:
      - searxng
    networks:
      - scraper-net

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    volumes:
      - ./searxng:/etc/searxng
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080
    restart: unless-stopped
    networks:
      - scraper-net

networks:
  scraper-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.70.0.0/24
